<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
if(!setting_bool('public_about_enabled',true))render_recovery_error_page(404,'صفحه درباره ما فعال نیست','این صفحه در حال حاضر از منوی عمومی کنار گذاشته شده است.',asset('menu/'),'بازگشت به منو');
$tableToken=trim((string)($_GET['table']??''));$menuKey=trim((string)($_GET['menu']??''));$tableContext=null;$invalidTableContext=false;
if($tableToken!==''){$stmt=db()->prepare('SELECT name,access_token FROM cafe_tables WHERE access_token=? AND active=1 LIMIT 1');$stmt->execute([$tableToken]);$tableContext=$stmt->fetch()?:null;$invalidTableContext=$tableContext===null;}
$menuParams=[];if($tableContext)$menuParams['table']=(string)$tableContext['access_token'];if($menuKey!==''&&preg_match('/^[A-Za-z0-9._-]{1,80}$/',$menuKey))$menuParams['menu']=$menuKey;$menuReturnUrl=asset('menu/').($menuParams?'?'.http_build_query($menuParams):'');
$font=menu_font();$name=setting('cafe_name','سکنا');$title=setting('about_title','درباره سکنا');$description=setting('seo_description','منوی کافه، رویدادها و راه‌های ارتباط با سکنا.');$logo=setting('logo_path');$primary=valid_hex_color(setting('primary_color','#365b4c'),'#365b4c');$accent=valid_hex_color(setting('accent_color','#b85c38'),'#b85c38');$background=valid_hex_color(setting('background_color','#f7f3ec'),'#f7f3ec');$social=social_links();$site=safe_external_url(setting('accommodation_site_url'));
$sameAs=[];foreach($social as $link){if($link['key']==='instagram_cafe')$sameAs[]=$link['url'];}
$schema=['@context'=>'https://schema.org','@type'=>'CafeOrCoffeeShop','name'=>$name,'url'=>canonical_asset('about.php'),'description'=>$description];if($logo)$schema['logo']=canonical_asset($logo);if(setting('public_phone'))$schema['telephone']=setting('public_phone');if(setting('public_address'))$schema['address']=['@type'=>'PostalAddress','streetAddress'=>setting('public_address'),'addressCountry'=>'IR'];if($sameAs)$schema['sameAs']=$sameAs;$schema['menu']=canonical_asset('menu/');
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= e($description) ?>"><meta name="theme-color" content="<?= e($primary) ?>"><link rel="canonical" href="<?= e(canonical_asset('about.php')) ?>"><meta property="og:title" content="<?= e($title.' | '.$name) ?>"><meta property="og:description" content="<?= e($description) ?>"><meta property="og:type" content="website"><meta property="og:url" content="<?= e(canonical_asset('about.php')) ?>"><?php if($logo): ?><meta property="og:image" content="<?= e(canonical_asset($logo)) ?>"><?php endif; ?><title><?= e($title.' | '.$name) ?></title><?= favicon_head_tags() ?><?= ui_font_head($font) ?><link rel="stylesheet" href="<?= e(asset('assets/css/tokens.css')) ?>"><link rel="stylesheet" href="<?= e(asset('assets/css/app.css')) ?>"><link rel="stylesheet" href="<?= e(asset('assets/css/responsive.css')) ?>"><link rel="stylesheet" href="<?= e(asset('assets/css/public-page.css')) ?>"><style>:root{--font-ui:<?= ui_font_family($font) ?>;--primary:<?= e($primary) ?>;--accent:<?= e($accent) ?>;--app-bg:<?= e($background) ?>;--on-primary:<?= e(contrast_text_color($primary)) ?>;--on-accent:<?= e(contrast_text_color($accent)) ?>}</style><script type="application/ld+json"><?= json_script($schema) ?></script></head><body class="public-page theme-<?= e(menu_theme()) ?> font-<?= e($font) ?>"><main class="public-shell"><?php if($invalidTableContext): ?><div class="alert alert-warning" role="alert"><?= ui_icon('warning') ?><div><strong>لینک میز معتبر نیست</strong><p>برای ادامه سفارش، QR میز فعلی را دوباره اسکن کن. انتخاب‌های میز دیگری به منوی عمومی منتقل نمی‌شوند.</p></div></div><?php endif; ?><header class="public-hero"><a class="public-brand" href="<?= e($menuReturnUrl) ?>"><?php if($logo): ?><img src="<?= e(asset($logo)) ?>" alt="لوگوی <?= e($name) ?>"><?php else: ?><span><?= ui_icon('coffee') ?></span><?php endif; ?><strong><?= e($name) ?></strong></a><div><span>آشنایی بیشتر</span><h1><?= e($title) ?></h1><p><?= nl2br(e(setting('about_intro','سکنا جایی برای قهوه، گفت‌وگو و تجربه‌های نزدیکه.'))) ?></p></div></header><section class="public-info-grid"><?php if(setting('public_address')): ?><article><span>نشانی</span><p><?= nl2br(e(setting('public_address'))) ?></p></article><?php endif; ?><?php if(setting('public_phone')): ?><article><span>تماس</span><a href="tel:<?= e(preg_replace('/[^0-9+]/','',en_digits(setting('public_phone')))) ?>" dir="ltr"><?= e(fa_digits(setting('public_phone'))) ?></a></article><?php endif; ?><article><span><?= $tableContext?'منوی میز':'منوی کافه' ?></span><a href="<?= e($menuReturnUrl) ?>"><?= $tableContext?'بازگشت به '.e(fa_digits((string)$tableContext['name'])):'دیدن منوی عمومی' ?></a></article></section>
<?php if(setting_bool('accommodation_enabled',true)&&$site): ?><section class="public-accommodation"><div><span>بیشتر از سکنا</span><h2><?= e(setting('accommodation_card_title','خانه سکنا رو هم می‌شناسی؟')) ?></h2><p><?= e(setting('accommodation_card_text','اقامت، گشت‌وگذار و تجربه غرب هرمزگان')) ?></p></div><div class="actions"><a class="btn btn-primary" target="_blank" rel="noopener" href="<?= e($site) ?>" data-metric="accommodation_click">سایت خانه سکنا</a><?php if($rooms=safe_external_url(setting('accommodation_rooms_url'))): ?><a class="btn btn-light" target="_blank" rel="noopener" href="<?= e($rooms) ?>">اتاق‌ها</a><?php endif; ?><?php if($tours=safe_external_url(setting('accommodation_tours_url'))): ?><a class="btn btn-light" target="_blank" rel="noopener" href="<?= e($tours) ?>">گشت‌ها</a><?php endif; ?></div></section><?php endif; ?>
<?php if($social): ?><section class="public-social"><span>راه‌های ارتباط</span><div class="social-link-grid"><?php foreach($social as $link): ?><a target="_blank" rel="noopener" href="<?= e($link['url']) ?>" data-metric="<?= e($link['key']==='whatsapp'?'whatsapp_click':'instagram_click') ?>"><span><?= ui_icon((string)$link['icon']) ?></span><strong><?= e($link['label']) ?></strong></a><?php endforeach; ?></div></section><?php endif; ?><footer><a href="<?= e($menuReturnUrl) ?>"><?= $tableContext?'بازگشت به منوی میز':'منوی کافه' ?></a><?php if($site): ?><span>·</span><a href="<?= e($site) ?>" target="_blank" rel="noopener">سایت خانه سکنا</a><?php endif; ?></footer></main><script>window.CAFE_METRIC_URL=<?= json_script(asset('api/metric.php')) ?>;window.CAFE_CSRF=<?= json_script(csrf_token()) ?>;fetch(window.CAFE_METRIC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({metric_key:'about_open',ref_id:0,csrf_token:window.CAFE_CSRF}),keepalive:true}).catch(()=>{});document.addEventListener('click',e=>{const a=e.target.closest('[data-metric]');if(a)fetch(window.CAFE_METRIC_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({metric_key:a.dataset.metric,ref_id:0,csrf_token:window.CAFE_CSRF}),keepalive:true}).catch(()=>{});});</script></body></html>
