#!/usr/bin/env python3
from pathlib import Path
root=Path(__file__).resolve().parents[1]
program=(root/'installer/windows/setup-ui/Program.cs').read_text(encoding='utf-8')
proj=(root/'installer/windows/setup-ui/Sokna.SetupUi.csproj').read_text(encoding='utf-8')
manifest=(root/'installer/windows/setup-ui/app.manifest').read_text(encoding='utf-8')
build=(root/'installer/windows/scripts/build-setup-ui.ps1').read_text(encoding='utf-8-sig')
prepare=(root/'installer/windows/scripts/prepare-shell-payload.ps1').read_text(encoding='utf-8-sig')
host=(root/'installer/windows/setup-host/Program.cs').read_text(encoding='utf-8')
package=(root/'installer/windows/wix/Package.wxs').read_text(encoding='utf-8')
bundle=(root/'installer/windows/wix/Bundle.wxs').read_text(encoding='utf-8')
workflow=(root/'.github/workflows/sokna-ci.yml').read_text(encoding='utf-8')

def need(cond,msg):
    if not cond: raise AssertionError(msg)
    print('PASS:',msg)

need('<OutputType>WinExe</OutputType>' in proj and '<UseWindowsForms>true</UseWindowsForms>' in proj and '<SelfContained>true</SelfContained>' in proj and '<PublishSingleFile>true</PublishSingleFile>' in proj,'Setup UI is a self-contained single-file Windows UI')
need('requestedExecutionLevel level="asInvoker"' in manifest and 'requireAdministrator' not in manifest,'Setup UI itself is non-elevated; elevation remains with Setup Host')
need('RightToLeft = RightToLeft.Yes' in program and 'RightToLeftLayout = true' in program and 'راه‌اندازی سکنا' in program,'Setup UI is Persian-first and true RTL')
need(all(term not in program for term in ['ownerهای canonical','Recovery Set / Backup','پس از Restart','Sokna Setup Host در بسته نصب وجود ندارد.']),'user-facing Setup copy avoids internal architecture jargon and mixed-language operational wording')
need('["app_url"] = "https://"' in program and '["require_web_server_preflight"] = true' in program and '["skip_https"] = false' in program,'Setup UI keeps local HTTPS and Apache preflight mandatory')
need('MinimumSize = new Size(720, 560)' in program and 'MinimumSize = new Size(120, 44)' in program,'Setup UI fits common cashier displays and keeps primary action touch-friendly')
need('["app_url"] = "https://"' in program and '["skip_https"] = false' in program and '["require_web_server_preflight"] = true' in program,'user-facing Setup always requires canonical local HTTPS and Apache preflight')
need('"نصب جدید"' in program and '"بازیابی روی رایانه جدید"' in program and '"تعمیر نصب موجود"' in program,'Setup UI exposes only canonical New/Recover/Repair modes')
need('CheckBox _https' not in program and 'CheckBox _requireWeb' not in program,'technical HTTPS/Apache disable switches are not exposed in the user-facing Setup UI')
need('RootsOverlap(appRoot, dataRoot)' in program and 'پوشه داده باید کاملاً خارج از پوشه برنامه باشد.' in program,'Setup UI rejects AppRoot/DataRoot overlap before elevation')
need('پوشه برنامه (قابل تغییر)' in program,'AppRoot default is presented as a configurable choice rather than a frozen install contract')
need('MinimumSize = new Size(128, 44)' in program and 'MinimumSize = new Size(96, 44)' in program and 'MinimumSize = new Size(88, 44)' in program,'primary, secondary and browse actions use the shared minimum operational target height')
need('UseSystemPasswordChar = true' in program and 'CreatePrivateTempDirectory' in program and 'icacls.exe' in program and '/inheritance:r' in program,'secret inputs are masked and written only under an explicitly private temp root')
need(program.index('temp = CreatePrivateTempDirectory()') < program.index('File.WriteAllTextAsync(setupConfig'),'private ACL exists before setup secret bytes are written')
need('"setup_config_file"' in program and '"recovery_passphrase_file"' in program and '"--plan-file"' in program,'Setup UI passes secret-bearing values by private files and invokes canonical plan contract')
need('Verb = "runas"' in program and 'SoknaSetupHost.exe' in program,'only canonical Setup Host crosses the elevation boundary')
need('20 => "پیکربندی سکنا آماده است' in program and '21 => "سلامت HTTPS محلی تأیید نشد' in program,'Setup UI distinguishes external Apache reload from failed local HTTPS health')
need(all(token not in program for token in ['CREATE TABLE','INSERT INTO','UPDATE print_','setup-machine.php','sc.exe','Start-Service','Stop-Service']),'Setup UI contains no database/service/business mutation owner')
need('Directory.Delete(temp, true)' in program and 'finally' in program,'private setup inputs are deleted after Setup Host exits')
need('dotnet publish' in build and '-r win-x64' in build and '--self-contained true' in build,'Setup UI has a deterministic x64 CI build owner')
need('[Parameter(Mandatory=$true)][string]$SetupUiExe' in prepare and "SoknaSetupUi.exe" in prepare,'verified installer shell includes the compiled Setup UI')
need('"SoknaSetupUi.exe"' in host,'Setup Host exact shell manifest requires the canonical Setup UI')
need('SoknaSetupUiShortcut' in package and 'راه‌اندازی و تعمیر سکنا' in package,'Start Menu exposes the canonical Persian Setup UI')
need('LaunchTarget="[ProgramFiles64Folder]SOKNA\\Cafe Local\\Installer\\SoknaSetupUi.exe"' in bundle,'Burn success page can launch the canonical Setup UI')
need('build-setup-ui.ps1' in workflow and ('-SetupUiExe' in workflow or 'SetupUiExe=' in workflow) and 'phase8b-setup-ui-contract.py' in workflow,'Windows CI builds, packages and contract-checks Setup UI')
print('Phase 8B Setup UI contract PASS.')
