from pathlib import Path
root=Path(__file__).resolve().parents[1]
def read(p): return (root/p).read_text(encoding='utf-8-sig')
def need(c,m):
    if not c: raise SystemExit('FAIL: '+m)
domain=read('modules/Supply/domain.php')
page=read('admin/purchases_batch.php')
purchases=read('admin/purchases.php')
mods=read('includes/modules.php')
routes=read('docs/architecture-migration-r2/ROUTE_OWNERS.CSV')
need('function supply_receive_batch_locked' in domain,'batch receipt owner missing')
need('Validate and lock every line before the first mutation.' in domain,'validate-all barrier missing')
need("supply_group_rows_locked($pdo,$groupKey,true)" in domain,'batch does not lock canonical preparing groups')
need('inventory_resolve_operation_quantity' in domain,'batch bypasses canonical inventory quantity validation')
need('supply_receive_preparing_locked($pdo' in domain,'batch must reuse canonical single receipt owner')
need("'supply.batch_received'" in domain,'batch audit event missing')
need('اقلام خارج از فهرست باید ابتدا جداگانه' in domain,'provisional-item policy missing')
need('supply_receive_batch_locked($pdo,$lines' in page,'batch page does not use domain owner')
need('beginTransaction()' in page and 'rollBack()' in page and 'commit()' in page,'batch page transaction boundary missing')
need('همه ردیف‌های انتخاب‌شده ابتدا بررسی می‌شوند' in page,'atomicity copy missing')
need('purchases_batch.php' in purchases,'canonical purchases surface does not expose batch receipt')
need('admin/purchases_batch.php' in mods and 'supply_receive_batch_locked()' in mods,'module registry not updated')
need('admin/purchases_batch.php,supply,operational' in routes,'route owner missing')
print('PASS r2 batch purchase contract: validate-all, atomic transaction, canonical receipt reuse, explicit provisional-item path')
