<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
require_login(['admin']);
sokna_module_require('reporting');
require dirname(__DIR__) . '/includes/panel_layout.php';
require_once dirname(__DIR__) . '/includes/reporting.php';
require_once dirname(__DIR__) . '/includes/xlsx_export.php';

function analytics_number(mixed $value, int $decimals = 0): string {if ($value === null || $value === '') return '—';$n=number_format((float)$value,$decimals,'.','');if($decimals>0)$n=rtrim(rtrim($n,'0'),'.');return fa_digits($n);}
function analytics_scalar(PDO $pdo,string $sql,array $params=[]):mixed{$st=$pdo->prepare($sql);$st->execute($params);$v=$st->fetchColumn();return $v===false?null:$v;}
function analytics_rows(PDO $pdo,string $sql,array $params=[]):array{$st=$pdo->prepare($sql);$st->execute($params);return $st->fetchAll();}
function analytics_snapshot_filter(string $alias,string $fromDate,string $toDate,string $shiftKey=''):array{return business_snapshot_filter_sql($alias,$fromDate,$toDate,$shiftKey);}

$pdo=db();
$range=report_range_resolve('30');
$fromBusiness=(string)$range['from'];$toBusiness=(string)$range['to'];$days=(int)$range['days'];
$shiftOptions=business_report_shift_options($fromBusiness,$toBusiness,true);
$showShiftFilter=count($shiftOptions)>1;
$shiftScope=(string)($_GET['shift']??'all');if(!isset($shiftOptions[$shiftScope]))$shiftScope='all';
$selectedShift=(!in_array($shiftScope,['all','compare'],true)&&isset($shiftOptions[$shiftScope]))?$shiftScope:'';
$previousToBusiness=(new DateTimeImmutable($fromBusiness))->modify('-1 day')->format('Y-m-d');
$previousFromBusiness=(new DateTimeImmutable($previousToBusiness))->modify('-'.($days-1).' days')->format('Y-m-d');
[$physicalStart,$physicalEnd]=business_date_range_bounds($fromBusiness,$toBusiness);$from=$physicalStart->format('Y-m-d H:i:s');$to=$physicalEnd->format('Y-m-d H:i:s');
$warning=(string)$range['error'];$guestShiftLimited=$selectedShift!=='';
$validSettlement=report_valid_settlement_sql('sr');
$saleLineSource=report_settlement_line_source_sql('sale');
$settlementWhere="$validSettlement AND sr.business_date>=? AND sr.business_date<=?";$settlementParams=[$fromBusiness,$toBusiness];if($selectedShift!==''){$settlementWhere.=' AND sr.business_shift_key=?';$settlementParams[]=$selectedShift;}
$previousWhere="$validSettlement AND sr.business_date>=? AND sr.business_date<=?";$previousParams=[$previousFromBusiness,$previousToBusiness];if($selectedShift!==''){$previousWhere.=' AND sr.business_shift_key=?';$previousParams[]=$selectedShift;}

try{
    $netSales=(int)(analytics_scalar($pdo,"SELECT COALESCE(SUM(sr.total-sr.tax_amount),0) FROM settlement_records sr WHERE $settlementWhere",$settlementParams)??0);
    $taxTotal=(int)(analytics_scalar($pdo,"SELECT COALESCE(SUM(sr.tax_amount),0) FROM settlement_records sr WHERE $settlementWhere",$settlementParams)??0);
    $collectedTotal=(int)(analytics_scalar($pdo,"SELECT COALESCE(SUM(sr.total),0) FROM settlement_records sr WHERE $settlementWhere",$settlementParams)??0);
    $prevSales=(int)(analytics_scalar($pdo,"SELECT COALESCE(SUM(sr.total-sr.tax_amount),0) FROM settlement_records sr WHERE $previousWhere",$previousParams)??0);
    $receiptCount=(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM settlement_records sr WHERE $settlementWhere",$settlementParams)??0);
    $billCount=(int)(analytics_scalar($pdo,"SELECT COUNT(DISTINCT sr.session_id) FROM settlement_records sr WHERE $settlementWhere",$settlementParams)??0);
    $avgCheck=$billCount>0?(int)round($collectedTotal/$billCount):null;
    $avgSession=analytics_scalar($pdo,"SELECT AVG(TIMESTAMPDIFF(MINUTE,ts.started_at,COALESCE(ts.ended_at,sr.settled_at))) FROM settlement_records sr JOIN table_sessions ts ON ts.id=sr.session_id WHERE $settlementWhere AND COALESCE(ts.ended_at,sr.settled_at)>=ts.started_at",$settlementParams);
    $tableCount=(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM cafe_tables WHERE active=1")??0);
    // Concurrent-table pressure cannot be truthfully scoped to a historical shift from the current session schema.
    $peakTables=$selectedShift===''?(int)(analytics_scalar($pdo,"SELECT COALESCE(MAX((SELECT COUNT(*) FROM table_sessions t2 WHERE t2.started_at<=t1.started_at AND COALESCE(t2.ended_at,?)>t1.started_at)),0) FROM table_sessions t1 WHERE t1.started_at>=? AND t1.started_at<?",[$to,$from,$to])??0):null;
    $salesByDay=analytics_rows($pdo,"SELECT sr.business_date d,SUM(sr.total-sr.tax_amount) total,COUNT(*) receipts,COUNT(DISTINCT sr.session_id) bills FROM settlement_records sr WHERE $settlementWhere GROUP BY sr.business_date ORDER BY d",$settlementParams);
    $salesByHour=analytics_rows($pdo,"SELECT HOUR(sr.settled_at) h,SUM(sr.total-sr.tax_amount) total,COUNT(*) receipts,COUNT(DISTINCT sr.session_id) bills FROM settlement_records sr WHERE $settlementWhere GROUP BY HOUR(sr.settled_at) ORDER BY total DESC LIMIT 8",$settlementParams);
    $itemImpactSql="SELECT MAX(sale.item_name) item_name,SUM(sale.quantity) qty,SUM(sale.net_amount) revenue FROM settlement_records sr JOIN $saleLineSource ON sale.settlement_id=sr.id WHERE $settlementWhere GROUP BY CASE WHEN sale.item_id IS NULL THEN CONCAT('snapshot:',sale.item_name,'|',sale.unit_price) ELSE CONCAT('id:',sale.item_id) END ORDER BY revenue DESC,qty DESC";
    $topItems=analytics_rows($pdo,$itemImpactSql." LIMIT 12",$settlementParams);
    [$orderWhere,$orderParams]=analytics_snapshot_filter('o',$fromBusiness,$toBusiness,$selectedShift);[$waiterWhere,$waiterParams]=analytics_snapshot_filter('w',$fromBusiness,$toBusiness,$selectedShift);
    $orderQuality=analytics_rows($pdo,"SELECT COUNT(*) total,AVG(TIMESTAMPDIFF(SECOND,o.created_at,o.accepted_at)) avg_accept_sec FROM orders o WHERE $orderWhere AND o.accepted_at IS NOT NULL",$orderParams);
    $waiterQuality=analytics_rows($pdo,"SELECT COUNT(*) total,AVG(TIMESTAMPDIFF(SECOND,w.created_at,w.accepted_at)) avg_response_sec FROM waiter_calls w WHERE $waiterWhere AND w.accepted_at IS NOT NULL",$waiterParams);
    if(!$guestShiftLimited){$metrics=analytics_rows($pdo,"SELECT metric_key,SUM(metric_value) total FROM menu_metrics_daily WHERE metric_date>=? AND metric_date<=? GROUP BY metric_key",[$fromBusiness,$toBusiness]);$metricMap=[];foreach($metrics as $r)$metricMap[(string)$r['metric_key']]=(int)$r['total'];$searches=analytics_rows($pdo,"SELECT normalized_term,MAX(display_term) display_term,SUM(search_count) search_count,SUM(zero_result_count) zero_result_count FROM menu_search_terms_daily WHERE metric_date>=? AND metric_date<=? GROUP BY normalized_term ORDER BY search_count DESC LIMIT 12",[$fromBusiness,$toBusiness]);}else{$metricMap=[];$searches=[];}
}catch(Throwable $e){
    if($warning==='')$warning='بخشی از داده‌های تحلیلی در دسترس نیست. قبل از تصمیم مدیریتی، سلامت اطلاعات سامانه را بررسی کنید.';
    error_log('management analytics: '.$e->getMessage());$netSales=$prevSales=$taxTotal=$collectedTotal=$receiptCount=$billCount=$tableCount=0;$peakTables=null;$avgCheck=$avgSession=null;$salesByDay=$salesByHour=$topItems=$orderQuality=$waiterQuality=$searches=[];$metricMap=[];
}
$comparisonRows=[];
if($shiftScope==='compare'){
    foreach(business_report_shift_identities($shiftOptions) as $key=>$label){$where="$validSettlement AND sr.business_date>=? AND sr.business_date<=? AND sr.business_shift_key=?";$params=[$fromBusiness,$toBusiness,$key];$sales=(int)(analytics_scalar($pdo,"SELECT COALESCE(SUM(sr.total-sr.tax_amount),0) FROM settlement_records sr WHERE $where",$params)??0);$receipts=(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM settlement_records sr WHERE $where",$params)??0);$bills=(int)(analytics_scalar($pdo,"SELECT COUNT(DISTINCT sr.session_id) FROM settlement_records sr WHERE $where",$params)??0);[$ow,$op]=analytics_snapshot_filter('o',$fromBusiness,$toBusiness,$key);[$ww,$wp]=analytics_snapshot_filter('w',$fromBusiness,$toBusiness,$key);[$sw,$sp]=analytics_snapshot_filter('s',$fromBusiness,$toBusiness,$key);$comparisonRows[]=['label'=>$label,'sales'=>$sales,'receipts'=>$receipts,'bills'=>$bills,'avg'=>$bills?(int)round($sales/$bills):0,'orders'=>(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM orders o WHERE $ow",$op)??0),'calls'=>(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM waiter_calls w WHERE $ww",$wp)??0),'sessions'=>(int)(analytics_scalar($pdo,"SELECT COUNT(*) FROM table_sessions s WHERE $sw",$sp)??0)];}
}
$outsideActivity=['orders'=>0,'calls'=>0,'sessions'=>0,'settlements'=>0,'total'=>0];try{$outsideActivity=business_outside_activity_counts($fromBusiness,$toBusiness);}catch(Throwable $e){error_log('analytics outside-shift audit: '.$e->getMessage());}
$salesChange=$prevSales>0?round(($netSales-$prevSales)*100/$prevSales,1):null;$orderRow=$orderQuality[0]??[];$waiterRow=$waiterQuality[0]??[];
$menuViews=$metricMap['menu_view']??0;$itemAdds=$metricMap['item_add']??0;$orderSubmits=$metricMap['order_submit']??0;$searchTotal=array_sum(array_map(static fn(array $r):int=>(int)$r['search_count'],$searches));$zeroTotal=array_sum(array_map(static fn(array $r):int=>(int)$r['zero_result_count'],$searches));$zeroRate=$searchTotal>0?round($zeroTotal*100/$searchTotal,1):null;

if(($_GET['action']??'')==='export'){
    $itemGroupCountSql="SELECT COUNT(*) FROM (SELECT 1 FROM settlement_records sr JOIN $saleLineSource ON sale.settlement_id=sr.id WHERE $settlementWhere GROUP BY CASE WHEN sale.item_id IS NULL THEN CONCAT('snapshot:',sale.item_name,'|',sale.unit_price) ELSE CONCAT('id:',sale.item_id) END) grouped_items";$itemGroupCount=(int)(analytics_scalar($pdo,$itemGroupCountSql,$settlementParams)??0);try{report_export_guard($itemGroupCount,'اقلام فروش');}catch(RuntimeException $e){flash('warning',$e->getMessage());$query=$_GET;unset($query['action']);redirect('analytics.php'.($query?'?'.http_build_query($query):''));}$allItemRows=analytics_rows($pdo,$itemImpactSql,$settlementParams);
    $scope=$shiftOptions[$shiftScope]??'کل روز';
    $summary=[[xlsx_cell('فروش و عملکرد سکنا','title',3)],[xlsx_cell('بازه: '.$range['label'].' · '.$scope,'meta',3)],[xlsx_cell('شاخص','header'),xlsx_cell('مقدار','header'),xlsx_cell('توضیح','header')],['فروش پس از تخفیف (پیش از مالیات)',xlsx_cell($netSales,'money'),'تسویه‌های معتبر و برگشت‌نخورده'],['مالیات',xlsx_cell($taxTotal,'money'),'مالیات ثبت‌شده روی اسناد'],['دریافتی نهایی',xlsx_cell($collectedTotal,'money'),'فروش به‌علاوه مالیات'],['رسید پرداخت معتبر',xlsx_cell($receiptCount,'integer'),'هر پرداخت مستقل'],['حساب میز تسویه‌شده',xlsx_cell($billCount,'integer'),'تعداد نشست‌های دارای تسویه معتبر'],['میانگین حساب میز',$avgCheck===null?'—':xlsx_cell($avgCheck,'money'),''],['میانگین مدت نشست',$avgSession===null?'—':xlsx_cell((float)$avgSession,'integer'),'دقیقه'],['بیشترین میز هم‌زمان',$peakTables===null?'در این شیفت قابل محاسبه نیست':xlsx_cell($peakTables,'integer'),'برای کل روز قابل محاسبه است']];
    $daily=[[xlsx_cell('فروش روزانه','title',3)],[xlsx_cell('بازه: '.$range['label'],'meta',3)],[xlsx_cell('روز کاری','header'),xlsx_cell('رسید پرداخت','header'),xlsx_cell('فروش','header')]];foreach($salesByDay as $r)$daily[]=[jalali_date_input((string)$r['d']),xlsx_cell((int)$r['receipts'],'integer'),xlsx_cell((int)$r['total'],'money')];
    $items=[[xlsx_cell('اقلام فروش','title',3)],[xlsx_cell('بازه کامل · درآمد آیتم پس از تخصیص تخفیف و پیش از مالیات است.','meta',3)],[xlsx_cell('آیتم','header'),xlsx_cell('تعداد','header'),xlsx_cell('درآمد','header')]];foreach($allItemRows as $r)$items[]=[(string)$r['item_name'],xlsx_cell((int)$r['qty'],'integer'),xlsx_cell((int)$r['revenue'],'money')];
    $sheets=[['name'=>'خلاصه','rows'=>$summary,'widths'=>[30,24,50],'freeze_row'=>3],['name'=>'فروش روزانه','rows'=>$daily,'widths'=>[22,16,24],'freeze_row'=>3,'auto_filter'=>'A3:C'.max(3,count($daily))],['name'=>'اقلام','rows'=>$items,'widths'=>[34,16,24],'freeze_row'=>3,'auto_filter'=>'A3:C'.max(3,count($items))]];
    if($comparisonRows){$rows=[[xlsx_cell('مقایسه شیفت‌ها','title',7)],[xlsx_cell('بازه: '.$range['label'],'meta',7)],[xlsx_cell('شیفت','header'),xlsx_cell('فروش','header'),xlsx_cell('رسید','header'),xlsx_cell('میانگین حساب','header'),xlsx_cell('سفارش','header'),xlsx_cell('فراخوان','header'),xlsx_cell('نشست','header')]];foreach($comparisonRows as $r)$rows[]=[(string)$r['label'],xlsx_cell((int)$r['sales'],'money'),xlsx_cell((int)$r['receipts'],'integer'),xlsx_cell((int)$r['avg'],'money'),xlsx_cell((int)$r['orders'],'integer'),xlsx_cell((int)$r['calls'],'integer'),xlsx_cell((int)$r['sessions'],'integer')];$sheets[]=['name'=>'مقایسه شیفت‌ها','rows'=>$rows,'widths'=>[20,22,14,22,14,14,14],'freeze_row'=>3,'landscape'=>true];}
    xlsx_download('sokna-sales-performance.xlsx',$sheets);
}

panel_header('فروش و عملکرد','analytics');
?>
<div class="panel-surface-stack">
<section class="report-shell"><div class="report-shell-head"><div><strong>فروش و عملکرد</strong><small>برای تصمیم مدیریتی بازه‌ای؛ مبالغ تومان و مبنا روز عملیاتی کافه است.</small></div><span class="report-range-summary"><?= e((string)$range['label']) ?></span></div><form method="get" class="report-filter-grid"><?php report_render_range_fields($range,'analyticsReport'); ?><?php if($showShiftFilter): ?><div class="form-group"><label for="analyticsShift">شیفت</label><select class="form-control" id="analyticsShift" name="shift" data-choice-mode="adaptive" data-choice-label="شیفت"><?php foreach($shiftOptions as $key=>$label): ?><option value="<?= e($key) ?>" <?= $shiftScope===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="report-filter-actions"><button class="btn btn-primary">نمایش</button><button class="btn btn-light" name="action" value="export">خروجی Excel</button></div></form></section>
<nav class="panel-subnav analytics-subnav" aria-label="بخش‌های گزارش"><a href="#analyticsOverview">نمای کلی</a><a href="#analyticsSales">فروش و منو</a><a href="#analyticsTables">میزها و ظرفیت</a><a href="#analyticsGuest">رفتار مهمان</a><a href="#analyticsOperations">کیفیت عملیات</a></nav>
<?php if($warning): ?><div class="alert alert-warning"><?= e($warning) ?></div><?php endif; ?>
<?php if((int)$outsideActivity['total']>0): ?><div class="report-exception-strip"><strong><?= fa_digits((int)$outsideActivity['total']) ?> رخداد خارج از ساعت شیفت</strong><span>جزئیات در گزارش عملیات؛ این رخدادها از آمار کل روز حذف نشده‌اند.</span></div><?php endif; ?>
<section id="analyticsOverview"><div class="metric-grid compact-kpi-grid"><article class="metric-card"><span>فروش پس از تخفیف</span><strong><?= e(toman_number($netSales)) ?></strong><small><?= $salesChange===null?'مقایسه قبلی کافی نیست':($salesChange>=0?'+':'').analytics_number($salesChange,1).'٪ نسبت به بازه قبل' ?></small></article><article class="metric-card"><span>مالیات</span><strong><?= e(toman_number($taxTotal)) ?></strong><small>جزء فروش محسوب نمی‌شود</small></article><article class="metric-card"><span>دریافتی نهایی</span><strong><?= e(toman_number($collectedTotal)) ?></strong><small>فروش + مالیات</small></article><article class="metric-card"><span>رسید پرداخت</span><strong><?= e(fa_digits($receiptCount)) ?></strong><small>هر پرداخت مستقل</small></article><article class="metric-card"><span>حساب میز</span><strong><?= e(fa_digits($billCount)) ?></strong><small>نشست‌های تسویه‌شده</small></article><article class="metric-card"><span>میانگین حساب میز</span><strong><?= $avgCheck===null?'—':e(toman_number($avgCheck)) ?></strong></article><article class="metric-card"><span>میانگین مدت نشست</span><strong><?= $avgSession===null?'—':e(analytics_number($avgSession,0).' دقیقه') ?></strong></article></div></section>
<?php if($comparisonRows): ?><section class="card"><div class="card-head"><div><h2>مقایسه شیفت‌ها</h2><small>فروش بر اساس شیفت ثبت‌شده هنگام تسویه؛ رخدادها بر اساس اطلاعات ثبت‌شده همان زمان.</small></div></div><div class="report-data-list" style="--report-metric-count:6"><?php foreach($comparisonRows as $r): ?><article class="report-data-row"><div class="report-data-primary"><strong><?= e((string)$r['label']) ?></strong><small><?= fa_digits((int)$r['receipts']) ?> رسید · <?= fa_digits((int)$r['bills']) ?> حساب</small></div><div class="report-data-metric"><span>فروش</span><strong><?= e(toman_number((int)$r['sales'])) ?></strong></div><div class="report-data-metric"><span>میانگین حساب</span><strong><?= e(toman_number((int)$r['avg'])) ?></strong></div><div class="report-data-metric"><span>سفارش</span><strong><?= fa_digits((int)$r['orders']) ?></strong></div><div class="report-data-metric"><span>فراخوان</span><strong><?= fa_digits((int)$r['calls']) ?></strong></div><div class="report-data-metric"><span>نشست</span><strong><?= fa_digits((int)$r['sessions']) ?></strong></div></article><?php endforeach; ?></div></section><?php endif; ?>
<section class="analytics-grid" id="analyticsSales"><article class="card table-card"><div class="card-head"><div><h2>فروش روزانه</h2><small>فقط اسناد تسویه معتبر و برگشت‌نخورده.</small></div></div><div class="data-table-wrap"><table class="data-table analytics-compact-table"><thead><tr><th>روز کاری</th><th>رسید</th><th>فروش</th></tr></thead><tbody><?php foreach($salesByDay as $r): ?><tr><td><?= e(fa_digits(jalali_date_input((string)$r['d']))) ?></td><td><?= e(fa_digits((int)$r['receipts'])) ?></td><td class="analytics-money-cell"><?= e(toman_number((int)$r['total'])) ?></td></tr><?php endforeach; ?><?php if(!$salesByDay): ?><tr><td colspan="3" class="empty-state">داده‌ای نیست.</td></tr><?php endif; ?></tbody></table></div></article><article class="card"><div class="card-head"><div><h2>اقلام اثرگذار</h2><small>درآمد آیتم پس از تخصیص تخفیف و پیش از مالیات است؛ برای مقایسه اقلام استفاده شود.</small></div></div><div class="report-data-list" style="--report-metric-count:2"><?php foreach($topItems as $r): ?><article class="report-data-row"><div class="report-data-primary"><strong><?= e((string)$r['item_name']) ?></strong></div><div class="report-data-metric"><span>تعداد</span><strong><?= e(fa_digits((int)$r['qty'])) ?></strong></div><div class="report-data-metric"><span>درآمد</span><strong><?= e(toman_number((int)$r['revenue'])) ?></strong></div></article><?php endforeach; ?><?php if(!$topItems): ?><div class="empty-state">داده‌ای نیست.</div><?php endif; ?></div></article></section>
<section class="analytics-grid" id="analyticsTables"><article class="card"><div class="card-head"><div><h2>میزها و فشار ظرفیت</h2><small>بر اساس نشست‌های واقعی میزها در این بازه.</small></div></div><div class="card-body"><div class="metric-grid"><article class="metric-card"><span>میز فعال</span><strong><?= e(fa_digits($tableCount)) ?></strong></article><article class="metric-card"><span>بیشترین میز هم‌زمان</span><strong><?= $peakTables===null?'—':e(fa_digits($peakTables)) ?></strong><small><?= $peakTables===null?'برای شیفت انتخاب‌شده از داده فعلی قابل محاسبه نیست':($tableCount>0?analytics_number($peakTables*100/$tableCount,0).'٪ از میزهای فعال':'—') ?></small></article></div></div></article><article class="card table-card"><div class="card-head"><div><h2>ساعت‌های پرفروش</h2><small>برای تشخیص بازه‌های فشار.</small></div></div><div class="data-table-wrap"><table class="data-table analytics-compact-table"><thead><tr><th>ساعت</th><th>رسید</th><th>فروش</th></tr></thead><tbody><?php foreach($salesByHour as $r): ?><tr><td><?= e(fa_digits(sprintf('%02d:00',(int)$r['h']))) ?></td><td><?= e(fa_digits((int)$r['receipts'])) ?></td><td class="analytics-money-cell"><?= e(toman_number((int)$r['total'])) ?></td></tr><?php endforeach; ?><?php if(!$salesByHour): ?><tr><td colspan="3" class="empty-state">داده‌ای نیست.</td></tr><?php endif; ?></tbody></table></div></article></section>
<section class="analytics-grid" id="analyticsGuest"><article class="card"><div class="card-head"><div><h2>رفتار مهمان</h2><small>روزانه و بدون اطلاعات هویتی مهمان ثبت می‌شود.</small></div></div><div class="card-body"><?php if($guestShiftLimited): ?><div class="empty-state compact">این داده‌ها برای شیفت جداگانه ثبت نمی‌شوند؛ «کل روز» را انتخاب کن.</div><?php else: ?><div class="metric-grid"><article class="metric-card"><span>بازدید منو</span><strong><?= e(fa_digits($menuViews)) ?></strong></article><article class="metric-card"><span>افزودن به سبد</span><strong><?= e(fa_digits($itemAdds)) ?></strong></article><article class="metric-card"><span>رویداد ثبت سفارش</span><strong><?= e(fa_digits($orderSubmits)) ?></strong></article><article class="metric-card"><span>جست‌وجوی بی‌نتیجه</span><strong><?= $zeroRate===null?'—':e(analytics_number($zeroRate,1).'٪') ?></strong></article></div><?php endif; ?></div></article><article class="card table-card"><div class="card-head"><div><h2>عبارت‌های جست‌وجو</h2><small>برای نام‌گذاری، برچسب و تشخیص نیاز پیدا نشده.</small></div></div><div class="data-table-wrap"><table class="data-table analytics-compact-table"><thead><tr><th>عبارت</th><th>جست‌وجو</th><th>بی‌نتیجه</th></tr></thead><tbody><?php foreach($searches as $r): ?><tr><td><?= e((string)$r['display_term']) ?></td><td><?= e(fa_digits((int)$r['search_count'])) ?></td><td><?= e(fa_digits((int)$r['zero_result_count'])) ?></td></tr><?php endforeach; ?><?php if(!$searches): ?><tr><td colspan="3" class="empty-state">داده‌ای برای این نمایش وجود ندارد.</td></tr><?php endif; ?></tbody></table></div></article></section>
<section id="analyticsOperations"><article class="card"><div class="card-head"><div><h2>کیفیت عملیات</h2><small>برای رخدادها و اقدامات کارکنان، گزارش عملیات را ببین.</small></div><a class="btn btn-light" href="operations_report.php?<?= e(http_build_query(report_range_query($range,['shift'=>$shiftScope]))) ?>">عملیات</a></div><div class="card-body"><div class="metric-grid"><article class="metric-card"><span>میانگین پذیرش سفارش</span><strong><?= e(human_duration_seconds(isset($orderRow['avg_accept_sec'])?(float)$orderRow['avg_accept_sec']:null)) ?></strong><small><?= e(fa_digits((int)($orderRow['total']??0))) ?> سفارش دارای زمان پذیرش</small></article><article class="metric-card"><span>میانگین پاسخ فراخوان</span><strong><?= e(human_duration_seconds(isset($waiterRow['avg_response_sec'])?(float)$waiterRow['avg_response_sec']:null)) ?></strong><small><?= e(fa_digits((int)($waiterRow['total']??0))) ?> فراخوان دارای پاسخ</small></article></div></div></article></section>
</div>
<?php panel_footer(); ?>
