<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
sokna_module_require('inventory');
require_any_capability(['inventory_view','inventory_cost_view','inventory_operations','inventory_finalize','inventory_manage']);
require dirname(__DIR__) . '/includes/panel_layout.php';
$pdo=db();inventory_seed_if_empty($pdo);$id=(int)($_GET['id']??0);$item=inventory_item($pdo,$id);if(!$item){flash('error','کالا پیدا نشد.');redirect('inventory.php');}
$user=current_user();$canCost=user_can_inventory_cost($user);$canManage=user_can_inventory_manage($user);$canOps=user_can_inventory_operate($user);$inventoryInitialized=inventory_initialized();
$displayAverageCost = $item['average_unit_cost'] === null ? null : (float)$item['average_unit_cost'] * ((string)$item['base_unit']==='count' ? 1 : 1000);
$units=inventory_purchase_units($pdo,$id,true);$stmt=$pdo->prepare('SELECT m.*,u.display_name actor_name FROM inventory_movements m LEFT JOIN users u ON u.id=m.actor_user_id WHERE m.inventory_item_id=? ORDER BY m.occurred_at DESC,m.id DESC LIMIT 30');$stmt->execute([$id]);$movements=$stmt->fetchAll();
panel_header((string)$item['name'],'inventory');
?>
<div class="panel-detail-nav"><a class="panel-back-link" href="inventory.php"><?= ui_icon('chevron-right') ?> بازگشت به موجودی</a><?php if($canManage): ?><div class="panel-utility-actions"><a class="panel-icon-action" href="inventory_item_form.php?id=<?= $id ?>" aria-label="ویرایش کالا" title="ویرایش کالا"><?= ui_icon('edit') ?></a></div><?php endif; ?></div><?php if($canOps&&$inventoryInitialized): ?><div class="inventory-toolbar-actions inventory-detail-task-actions"><a class="btn btn-primary" href="inventory_receive.php?item_id=<?= $id ?>">ثبت ورود</a><a class="btn btn-light" href="inventory_waste.php?item_id=<?= $id ?>">ثبت ضایعات</a></div><?php endif; ?>
<div class="inventory-summary"><div class="summary-cell"><small>موجودی فعلی</small><strong><?= e(inventory_format_quantity((int)$item['quantity_base'],(string)$item['base_unit'])) ?></strong></div><div class="summary-cell"><small>حد هشدار</small><strong><?= (int)$item['warning_threshold']>0?e(inventory_format_quantity((int)$item['warning_threshold'],(string)$item['base_unit'])):'بدون حد' ?></strong></div><div class="summary-cell"><small>میانگین هزینه</small><?php if($canCost): ?><strong><?= $item['average_unit_cost']!==null?e(toman((int)round($displayAverageCost ?? 0))):'نامشخص' ?></strong><span class="summary-note"><?= $item['average_unit_cost']!==null&&in_array((string)$item['base_unit'],['g','ml'],true)?'برای هر ۱۰۰۰ '.e(inventory_base_unit_labels()[(string)$item['base_unit']]):'برای هر واحد پایه' ?></span><?php else: ?><strong>مخفی</strong><?php endif; ?></div></div>
<div class="panel-surface-stack inventory-item-sections">
<section class="card"><div class="card-head"><div><h2>مشخصات کالا</h2><small><?= e(inventory_category_labels()[(string)$item['category']]??(string)$item['category']) ?> · <?= e(inventory_department_labels()[(string)$item['default_department']]??'مشترک') ?></small></div><?php if((string)$item['review_status']==='needs_review'): ?><span class="inventory-status needs-review">نیاز به تأیید</span><?php endif; ?></div><div class="card-body"><div class="inventory-purchase-unit-list"><?php if(!$units): ?><div class="recipe-empty-note">واحد خرید جداگانه‌ای تعریف نشده است.</div><?php endif; ?><?php foreach($units as $unit): ?><div class="inventory-purchase-unit"><div><strong><?= e((string)$unit['name']) ?></strong><small><?= (string)$unit['conversion_mode']==='actual_quantity'?'مقدار واقعی هنگام ورود':($unit['base_quantity']===null?'تبدیل هنوز مشخص نیست':e(inventory_format_quantity((int)$unit['base_quantity'],(string)$item['base_unit']))) ?></small></div><?php if((string)$unit['review_status']==='needs_review'): ?><span class="inventory-status needs-review">نیاز به تأیید</span><?php endif; ?></div><?php endforeach; ?></div></div></section>
<section class="card"><div class="card-head"><div><h2>۳۰ ثبت اخیر انبار</h2><small>ورود، مصرف فروش، ضایعات و شمارش</small></div><a class="btn btn-sm btn-light" href="inventory.php?tab=movements&item=<?= $id ?>">همه سوابق</a></div><div class="card-body"><div class="inventory-movement-list"><?php if(!$movements): ?><div class="inventory-empty">هنوز سابقه‌ای برای این کالا ثبت نشده است.</div><?php endif; ?><?php foreach($movements as $m): ?><article class="inventory-movement"><div class="movement-main"><strong><?= e(inventory_movement_labels()[(string)$m['movement_type']]??(string)$m['movement_type']) ?></strong><small><?= e(format_jalali_compact((string)$m['occurred_at'])) ?> · <?= e((string)($m['actor_name']?:'سامانه')) ?></small></div><div class="movement-qty"><strong><?= e(inventory_format_quantity((int)$m['quantity_base'],(string)$m['base_unit'])) ?></strong><small><?= e($m['department']?(inventory_department_labels()[(string)$m['department']]??(string)$m['department']):'—') ?></small></div><div class="movement-cost"><?php if($canCost): ?><strong><?= $m['total_cost_delta']!==null?e(toman(abs((int)$m['total_cost_delta']))):'هزینه نامشخص' ?></strong><?php else: ?><span class="inventory-cost-hidden">هزینه مخفی</span><?php endif; ?></div><div class="movement-action"><small><?= e((string)($m['note']?:'—')) ?></small></div></article><?php endforeach; ?></div></div></section>
</div>
<?php panel_footer(); ?>
