<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
require_login(['admin']);
require dirname(__DIR__) . '/includes/panel_layout.php';
$id=(int)($_GET['id']??$_POST['id']??0);$sheet=($_GET['sheet']??'')==='1';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf($_POST['csrf_token']??null);$action=(string)($_POST['action']??'');
 try{if($id<1)throw new RuntimeException('میز معتبر انتخاب نشده است.');$pdo=db();$pdo->beginTransaction();$st=$pdo->prepare('SELECT id,name,access_token,previous_access_token FROM cafe_tables WHERE id=? FOR UPDATE');$st->execute([$id]);$t=$st->fetch();if(!$t)throw new RuntimeException('میز پیدا نشد.');
  if($action==='rotate'){$reason=text_substr(trim((string)($_POST['reason']??'')),0,180);$new=unique_table_access_token($pdo);$pdo->prepare('UPDATE cafe_tables SET previous_access_token=access_token,access_token=?,qr_rotated_at=NOW(),qr_rotated_by_user_id=? WHERE id=?')->execute([$new,(int)current_user()['id'],$id]);audit_log_write('table.qr_rotated','cafe_table',$id,['table_name'=>$t['name'],'reason'=>$reason?:null]);flash('success','QR جایگزین فعال شد؛ QR قبلی بلافاصله از اعتبار خارج شد.');}
  elseif($action==='restore'){$prev=trim((string)($t['previous_access_token']??''));if($prev==='')throw new RuntimeException('QR قبلی برای بازگردانی وجود ندارد.');$pdo->prepare('UPDATE cafe_tables SET access_token=?,previous_access_token=?,qr_rotated_at=NOW(),qr_rotated_by_user_id=? WHERE id=?')->execute([$prev,(string)$t['access_token'],(int)current_user()['id'],$id]);audit_log_write('table.qr_restored','cafe_table',$id,['table_name'=>$t['name']]);flash('success','QR قبلی دوباره فعال شد.');}
  else throw new RuntimeException('عملیات QR معتبر نیست.');$pdo->commit();
 }catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('qr action: '.$e->getMessage());flash('error',safe_business_error_message($e,'عملیات QR انجام نشد.'));}
 redirect('qr.php?id='.$id);
}
$params=[];$where=$sheet?'WHERE t.active=1':($id?'WHERE t.id=?':'WHERE 1=1');if($id&&!$sheet)$params[]=$id;
$st=db()->prepare("SELECT t.*,u.display_name qr_rotated_by_name FROM cafe_tables t LEFT JOIN users u ON u.id=t.qr_rotated_by_user_id $where ORDER BY COALESCE(t.zone_label,''),t.table_number,t.id");$st->execute($params);$tables=$st->fetchAll();$single=$id&&$tables?$tables[0]:null;
$canonical=app_canonical_url();$https=str_starts_with(strtolower($canonical),'https://');
panel_header($sheet?'برگه چاپ QR':($single?'QR '.fa_digits((string)$single['name']):'مرکز QR میزها'),'tables');
?>
<div class="no-print <?= (!$single||$sheet)?'panel-balanced-actions qr-page-actions':'panel-page-actions' ?>"><?php if(!$single&&!$sheet): ?><a class="btn btn-primary" href="?sheet=1"><?= ui_icon('print') ?> برگه چاپ همه QRها</a><a class="btn btn-light" href="tables.php">بازگشت به میزها</a><?php elseif($sheet): ?><button class="btn btn-primary" type="button" id="printQrSheet"><?= ui_icon('print') ?> چاپ / ذخیره PDF</button><a class="btn btn-light" href="qr.php">بازگشت به مرکز QR</a><?php else: ?><a class="btn btn-light" href="tables.php">بازگشت به میزها</a><?php endif; ?></div>
<?php if(!$sheet&&!$single): ?>
<div class="panel-surface-stack qr-center-stack">
<?php if(!$https): ?><div class="notice warning qr-domain-warning"><div class="panel-copy-stack"><strong>آدرس اصلی QRها نیاز به بررسی دارد.</strong><span class="muted">پیش از چاپ QRهای جدید، آدرس اصلی سامانه را روی HTTPS تنظیم کنید.</span></div><a class="btn btn-sm btn-light" href="settings.php#settingsDomain">بررسی تنظیمات</a></div><?php endif; ?>
<section class="card qr-table-list-card"><div class="card-head"><div><h2>میزها</h2><small><?= fa_digits(count($tables)) ?> میز · برای مشاهده، دانلود یا آزمایش QR، همان میز را باز کنید.</small></div></div><div class="panel-list-card qr-table-list"><?php foreach($tables as $t): ?><a class="qr-table-row" href="?id=<?= (int)$t['id'] ?>"><span class="qr-table-identity"><strong><?= e(fa_digits((string)$t['name'])) ?></strong><?php if(trim((string)($t['zone_label']??''))!==''): ?><small><?= e(fa_digits((string)$t['zone_label'])) ?></small><?php endif; ?></span><span class="panel-status-badge <?= (int)$t['active']===1?'is-ok':'' ?>"><?= (int)$t['active']===1?'فعال':'غیرفعال' ?></span><span class="qr-table-open" aria-hidden="true"><?= ui_icon('chevron-left') ?></span></a><?php endforeach; ?></div></section>
</div>
<?php elseif($single): $url=table_menu_url((string)$single['access_token']); ?>
<?php if(!(int)$single['active']): ?><div class="alert alert-warning"><strong>این میز غیرفعال است.</strong> QR پس از فعال‌شدن میز قابل استفاده خواهد بود.</div><?php endif; ?>
<div class="panel-surface-stack qr-single-stack"><div class="qr-grid is-single" id="qrSheet"><section class="card qr-card" data-qr-card data-file="table-<?= e((string)($single['table_number']??$single['id'])) ?>"><div class="qr-vector" data-qr="<?= e($url) ?>"></div><h3><?= e(fa_digits((string)$single['name'])) ?></h3><p><?= e(fa_digits((string)($single['zone_label']?:'منوی کافه سکنا'))) ?></p><div class="qr-link-row"><code class="qr-link" dir="ltr" title="<?= e($url) ?>"><?= e($url) ?></code><button class="btn btn-sm btn-light copy-qr-link" type="button">کپی لینک</button></div><div class="qr-card-actions"><button class="btn btn-sm btn-primary download-qr-svg" type="button">دانلود SVG</button><button class="btn btn-sm btn-light download-qr-png" type="button">دانلود PNG</button><a class="btn btn-sm btn-light" target="_blank" rel="noopener" href="<?= e($url) ?>">آزمایش لینک</a></div></section></div>
<section class="card qr-security-summary"><div class="card-head"><div><h2>مدیریت و امنیت QR</h2><small>با ابطال، QR فعلی همان لحظه از کار می‌افتد و QR جدید ساخته می‌شود. پس از ساخت، نسخه جدید را چاپ و جایگزین کنید.</small></div><span class="badge"><?= $single['qr_rotated_at']?'آخرین تغییر ثبت شده':'QR اولیه' ?></span></div><div class="card-body qr-security-grid"><div class="qr-security-status"><strong><?= (int)$single['active']===1?'QR فعال فعلی':'QR آماده برای فعال‌سازی میز' ?></strong><span><?= (int)$single['active']===1?'فقط همین QR منوی این میز را باز می‌کند.':'تا وقتی میز غیرفعال است، اسکن این QR سفارش‌گیری را باز نمی‌کند.' ?></span><?php if($single['qr_rotated_at']): ?><small>آخرین تغییر: <?= e(format_jalali_datetime((string)$single['qr_rotated_at'])) ?></small><?php endif; ?></div><div class="qr-security-actions"><?php if(!empty($single['previous_access_token'])): ?><form method="post" data-confirm="QR قبلی دوباره معتبر می‌شود و QR فعلی جایگزین آن خواهد شد." data-confirm-title="بازگردانی QR قبلی؟" data-confirm-ok="بازگردانی QR"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$single['id'] ?>"><button class="btn btn-outline" name="action" value="restore">بازگردانی QR قبلی</button></form><?php endif; ?><details class="qr-rotation-control"><summary class="btn btn-danger">ابطال فوری و ساخت QR جدید</summary><div><p>فقط برای QR آسیب‌دیده یا در معرض سوءاستفاده استفاده کنید؛ پس از ساخت، QR جدید را چاپ و جایگزین کنید.</p><form method="post" data-confirm="QR فعلی همان لحظه از کار می‌افتد و QR جدید ساخته می‌شود؛ نسخه چاپ‌شده باید جایگزین شود." data-confirm-title="ابطال QR فعلی؟" data-confirm-ok="ابطال و ساخت QR جدید" data-confirm-danger="1"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$single['id'] ?>"><label>دلیل اختیاری<input class="form-control" name="reason" maxlength="180"></label><button class="btn btn-danger" name="action" value="rotate">ساخت QR جایگزین</button></form></div></details></div></div></section></div>

<script src="<?= e(asset('assets/js/qrcode-local.js')) ?>"></script><script>(()=>{const c=document.querySelector('[data-qr-card]'),h=c?.querySelector('.qr-vector');if(!c||!h)return;const text=h.dataset.qr;h.innerHTML=CafeQRCode.svg(text,900);const dl=(b,n)=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};c.querySelector('.download-qr-svg').onclick=()=>dl(new Blob([CafeQRCode.svg(text,1200)],{type:'image/svg+xml;charset=utf-8'}),c.dataset.file+'-qr.svg');c.querySelector('.download-qr-png').onclick=()=>{const x=document.createElement('canvas');CafeQRCode.draw(x,text,1200);x.toBlob(b=>b&&dl(b,c.dataset.file+'-qr.png'),'image/png')};c.querySelector('.copy-qr-link')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(text);CafeUI.toast('لینک میز کپی شد.');}catch(_){CafeUI.toast('کپی لینک انجام نشد.','error');}});})();</script>
<?php else: ?>
<div class="qr-grid" id="qrSheet"><?php foreach($tables as $t):$url=table_menu_url((string)$t['access_token']);?><section class="card qr-card" data-qr-card><div class="qr-vector" data-qr="<?= e($url) ?>"></div><h3><?= e(fa_digits((string)$t['name'])) ?></h3><p><?= e(fa_digits((string)($t['zone_label']?:'منوی کافه سکنا'))) ?></p></section><?php endforeach; ?></div><script src="<?= e(asset('assets/js/qrcode-local.js')) ?>"></script><script>(()=>{document.querySelectorAll('[data-qr-card] .qr-vector').forEach(h=>h.innerHTML=CafeQRCode.svg(h.dataset.qr,900));document.getElementById('printQrSheet')?.addEventListener('click',()=>window.print())})();</script>
<?php endif; panel_footer(); ?>
