<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';require_login(['admin']);require dirname(__DIR__) . '/includes/panel_layout.php';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf($_POST['csrf_token']??null);$id=(int)($_POST['id']??0);$action=(string)($_POST['action']??'');$pdo=db();try{if($action==='set_active'){$desiredRaw=(string)($_POST['desired_active']??'');if(!in_array($desiredRaw,['0','1'],true))throw new RuntimeException('وضعیت درخواستی معتبر نیست.');$desired=(int)$desiredRaw;$pdo->beginTransaction();$st=$pdo->prepare('SELECT id,title,active FROM tags WHERE id=? FOR UPDATE');$st->execute([$id]);$before=$st->fetch();if(!$before)throw new RuntimeException('برچسب پیدا نشد.');if((int)$before['active']!==$desired){$pdo->prepare('UPDATE tags SET active=? WHERE id=?')->execute([$desired,$id]);audit_log_write('menu.tag_active_changed','tag',$id,['title'=>$before['title'],'active_before'=>(int)$before['active'],'active_after'=>$desired]);}$pdo->commit();flash('success',$desired?'برچسب فعال شد.':'برچسب غیرفعال شد.');}elseif($action==='delete'){$pdo->beginTransaction();$st=$pdo->prepare('SELECT id,title FROM tags WHERE id=? FOR UPDATE');$st->execute([$id]);$before=$st->fetch();if(!$before)throw new RuntimeException('برچسب پیدا نشد.');$countStmt=$pdo->prepare('SELECT COUNT(*) FROM item_tags WHERE tag_id=?');$countStmt->execute([$id]);$itemCount=(int)$countStmt->fetchColumn();$pdo->prepare('DELETE FROM tags WHERE id=?')->execute([$id]);audit_log_write('menu.tag_deleted','tag',$id,['title'=>$before['title'],'affected_items'=>$itemCount]);$pdo->commit();flash('success','برچسب حذف شد.');}else throw new RuntimeException('عملیات معتبر نیست.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('tag action: '.$e->getMessage());flash('error',safe_business_error_message($e,'این تغییر انجام نشد.'));}redirect('tags.php');}
$filter=(string)($_GET['type']??'all');if(!in_array($filter,['all','marketing','attribute'],true))$filter='all';$where=$filter==='all'?'':'WHERE t.tag_type='.db()->quote($filter);$tags=db()->query("SELECT t.*,COUNT(it.item_id) item_count FROM tags t LEFT JOIN item_tags it ON it.tag_id=t.id $where GROUP BY t.id ORDER BY t.tag_type,t.sort_order,t.id")->fetchAll();
panel_header('برچسب‌های منو','tags');
panel_subnav(['items'=>['items.php','مدیریت منو'],'order'=>['items.php?view=arrange','چیدمان'],'tags'=>['tags.php','برچسب‌ها'],'transfer'=>['menu_transfer.php','ورود و خروجی']], 'tags', 'مدیریت آیتم‌های منو');
?>
<div class="toolbar"><div class="filter-pills"><a class="<?= $filter==='all'?'active':'' ?>" href="?type=all">همه</a><a class="<?= $filter==='marketing'?'active':'' ?>" href="?type=marketing">بازاریابی</a><a class="<?= $filter==='attribute'?'active':'' ?>" href="?type=attribute">ویژگی محصول</a></div><a class="btn btn-primary" href="tag_form.php">برچسب جدید</a></div>
<section class="card"><div class="card-head"><div><h2>کتابخانه برچسب‌ها</h2></div></div><div class="tag-list-v1292"><?php if(!$tags): ?><div class="empty-state">برچسبی برای نمایش وجود ندارد.</div><?php endif; ?><?php foreach($tags as $tag): ?><article class="tag-row-v1292"><div><span class="menu-tag tag-<?= e($tag['color_key']) ?>"><?= e(trim(($tag['icon']?:'').' '.$tag['title'])) ?></span><small><?= $tag['tag_type']==='marketing'?'بازاریابی':'ویژگی محصول' ?> · <?= e(fa_digits((int)$tag['item_count'])) ?> آیتم · <?= $tag['active']?'فعال':'غیرفعال' ?></small></div><div class="actions"><a class="btn btn-sm btn-light" href="tag_form.php?id=<?= (int)$tag['id'] ?>">ویرایش</a><form method="post"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$tag['id'] ?>"><input type="hidden" name="desired_active" value="<?= $tag['active']?'0':'1' ?>"><button class="btn btn-sm btn-outline" name="action" value="set_active"><?= $tag['active']?'غیرفعال‌کردن':'فعال‌کردن' ?></button></form><form method="post" data-confirm="این برچسب از همه آیتم‌ها حذف می‌شود." data-confirm-title="حذف برچسب؟" data-confirm-ok="حذف برچسب" data-confirm-danger="1"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$tag['id'] ?>"><button class="btn btn-sm btn-danger" name="action" value="delete">حذف</button></form></div></article><?php endforeach; ?></div></section>
<?php panel_footer(); ?>
